# Generated by Django 5.0.3 on 2026-03-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdgenerator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrun',
            name='github_run_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
