# Generated by Django 5.2.13 on 2026-07-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdgenerator', '0002_githubrun_github_run_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrun',
            name='run_ids',
            field=models.TextField(blank=True, null=True, verbose_name='全部工作流运行ID'),
        ),
        migrations.AlterField(
            model_name='githubrun',
            name='status',
            field=models.CharField(max_length=100, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='githubrun',
            name='uuid',
            field=models.CharField(max_length=100, verbose_name='UUID'),
        ),
    ]
